---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.14.4
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/infra/cert-manager/values.yaml
    - repoURL: https://github.com/nrwiersma/homelab.git
      targetRevision: HEAD
      path: infra/cert-manager
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
