---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.9.11
      helm:
        releaseName: external-secrets
      valueFiles:
        - $values/infra/external-secrets/values.yaml
    - repoURL: https://github.com/nrwiersma/homelab.git
      targetRevision: init
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
