---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nrwiersma/homelab.git
    targetRevision: HEAD
    path: global
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
