---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
spec:
  project: mon
  sources:
    - repoURL: https://helm.influxdata.com/
      chart: influxdb2
      targetRevision: 2.1.2
      helm:
        releaseName: influxdb2
        valueFiles:
          - $values/mon/influxdb/values.yaml
    - repoURL: https://github.com/nrwiersma/homelab.git
      targetRevision: HEAD
      path: mon/influxdb
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
