---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: mon
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 72.4.0
      helm:
        releaseName: kube-prometheus
        valueFiles:
          - $values/mon/kube-prom/values.yaml
    - repoURL: https://github.com/nrwiersma/homelab.git
      targetRevision: HEAD
      path: mon/kube-prom
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - kind: Service
      jqPathExpressions:
        - .spec.ports[].nodePort
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
