---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: mon
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 56.6.1
      helm:
        releaseName: kube-prometheus
        valueFiles:
          - $values/mon/kube-prom/values.yaml
    - repoURL: https://github.com/nrwiersma/homelab.git
      targetRevision: prom
      path: mon/kube-prom
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
