---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-secrets
    creationPolicy: Owner
  data:
    - secretKey: slack-api-url
      remoteRef:
        key: slack-api-url
        property: URL
