---
defaultRules:
  rules:
    etcd: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

alertmanager:
  config:
    receivers:
      - name: 'null' # TODO:
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: alerts.wiersma.tech.
      external-dns.alpha.kubernetes.io/ttl: 5m
    type: LoadBalancer
    port: 80
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 25m
        memory: 32Mi

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 3d
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        cpu: 1
        memory: 2Gi

grafana:
  plugins: []
  grafana.ini:
    auth:
      anonymous:
        enabled: true
        org_role: Admin
      basic:
        enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 500Mi

  sidecar:
    resources:
      requests:
        cpu: 5m
        memory: 64Mi
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: mon.wiersma.tech.
      external-dns.alpha.kubernetes.io/ttl: 5m
    type: LoadBalancer

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 5m
      memory: 16Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 5m
      memory: 128Mi
