---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme
spec:
  acme:
    email: nick@wiersma.co.za
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: wiersma-tech
            serviceAccountSecretRef:
              name: google-dns
              key: credentials.json
