---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-dns
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: google-dns
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: google-dns
        property: credentials.json
