---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  serviceName: jellyfin
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: ghcr.io/linuxserver/jellyfin:10.10.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8096
            - name: https
              containerPort: 8920
            - name: dlna-udp
              containerPort: 1900
              protocol: UDP
            - name: discovery-udp
              containerPort: 7359
              protocol: UDP
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: http://jellyfin.wiersma.tech
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: http
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
            limits:
              memory: 2Gi
          volumeMounts:
            - name: jellyfin-config
              mountPath: "/config"
            - name: series
              mountPath: "/media/series"
            - name: movies
              mountPath: "/media/movies"
      volumes:
        - name: series
          persistentVolumeClaim:
            claimName: series
        - name: movies
          persistentVolumeClaim:
            claimName: movies
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: jellyfin-config
        labels:
          recurring-job-group.longhorn.io/backup: enabled
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-tcp
  labels:
    app.kubernetes.io/name: jellyfin-tcp
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jellyfin.wiersma.tech.
    external-dns.alpha.kubernetes.io/ttl: 5m
    metallb.universe.tf/loadBalancerIPs: "10.0.2.20"
    metallb.universe.tf/allow-shared-ip: "jellyfin"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: jellyfin
  ports:
    - name: http
      port: 80
      targetPort: 8096
    - name: https
      port: 443
      targetPort: 8920
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-udp
  labels:
    app.kubernetes.io/name: jellyfin-udp
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.2.20"
    metallb.universe.tf/allow-shared-ip: "jellyfin"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: jellyfin
  ports:
    - name: dlna-udp
      protocol: UDP
      port: 1900
      targetPort: 1900
    - name: discovery-udp
      protocol: UDP
      port: 7359
      targetPort: 7359