---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: series
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: media.wiersma.tech/Series##
    volumeAttributes:
      source: //media.wiersma.tech/Series
    nodeStageSecretRef:
      name: samba-credentials
      namespace: media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: media.wiersma.tech/Movies##
    volumeAttributes:
      source: //media.wiersma.tech/Movies
    nodeStageSecretRef:
      name: samba-credentials
      namespace: media
