---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: series
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
