---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: series
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-backup
  labels:
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
