---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
spec:
  replicas: 1
  serviceName: radarr
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      containers:
        - name: radarr
          image: ghcr.io/linuxserver/radarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              memory: 2Gi
          volumeMounts:
            - name: radarr-config
              mountPath: "/config"
            - name: movies
              mountPath: "/movies"
            - name: downloads
              mountPath: "/downloads"
      volumes:
        - name: movies
          persistentVolumeClaim:
            claimName: movies
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: radarr-config
        labels:
          recurring-job-group.longhorn.io/backup: enabled
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        volumeMode: Filesystem

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: radarr.wiersma.tech.
    external-dns.alpha.kubernetes.io/ttl: 5m
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: radarr
  ports:
    - name: radarr
      port: 80
      targetPort: 7878
