---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-gcp-backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: longhorn-gcp-backups
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: longhorn-gcp-backups
        property: access-key
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: longhorn-gcp-backups
        property: endpoints
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: longhorn-gcp-backups
        property: secret
