---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: google-dns
        property: credentials.json
