---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - ../../base
  - external-dns.externalsecret.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: external-dns
    path: patches/external-dns.deployment.yaml
