---
apiVersion: v1
kind: Service
metadata:
  name: samba-udp
  labels:
    app.kubernetes.io/name: samba
spec:
  type: ClusterIP
  ports:
    - name: wins
      port: 137
      protocol: UDP
      targetPort: wins
    - name: datagram
      port: 138
      protocol: UDP
      targetPort: datagram
  selector:
    app.kubernetes.io/name: samba
---
apiVersion: v1
kind: Service
metadata:
  name: samba-tcp
  labels:
    app.kubernetes.io/name: samba
spec:
  type: ClusterIP
  ports:
    - name: session
      port: 139
      protocol: TCP
      targetPort: session
    - name: cifs
      port: 445
      protocol: TCP
      targetPort: cifs
  selector:
    app.kubernetes.io/name: samba
