---
apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-config
data:
  smb.conf: |-
    [global]
    access based share enum = no
    hide files = /lost+found/
    hide unreadable = no
    inherit permissions = yes
    load printers = no
    log file = /var/log/samba/log.%m
    logging = file
    max log size = 1000
    security = user
    server min protocol = SMB2
    server role = standalone server
    smb ports = 445
    workgroup = WORKGROUP
    vfs objects = catia fruit streams_xattr
    fruit:aapl = yes
    fruit:nfs_aces = no
    fruit:model = TimeCapsule8,119
    fruit:metadata = stream
    fruit:veto_appledouble = no
    fruit:posix_rename = yes
    fruit:zero_file_id = yes
    fruit:wipe_intentionally_left_blank_rfork = yes
    fruit:delete_empty_adfiles = yes
    [TimeMachine]
    comment = Time Machine Backup
    path = /opt/media
    writable = yes
    browseable = yes
    read only = no
    valid users = media
    inherit acls = yes
    fruit:time machine = yes
    fruit:time machine max size = 800G
    [Movies]
    path = /opt/movies
    read only = no
    valid users = media
    [Series]
    path = /opt/series
    read only = no
    valid users = media
    [Downloads]
    path = /opt/downloads
    read only = no
    valid users = media
