---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - ../../base
  - configmap.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: samba
    path: patches/samba.statefulset.yaml
  - target:
      version: v1
      kind: Service
      name: samba-udp
    path: patches/samba-udp.service.yaml
  - target:
      version: v1
      kind: Service
      name: samba-tcp
    path: patches/samba-tcp.service.yaml

images:
  - name: mbentley/timemachine
    newTag: smb-20250219
