---
resources:
  requests:
    cpu: 50m
    memory: 100Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi

certController:
  resources:
    requests:
      cpu: 10m
      memory: 150Mi

serviceMonitor:
  enabled: true
