---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
spec:
  commonName: argocd.wiersma.tech
  dnsNames:
    - argocd.wiersma.tech
  subject:
    organizations:
      - Wiersma
  secretName: argocd-server-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: acme
