---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: google-oidc
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: google-oidc
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: client_id
      remoteRef:
        key: google-oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: google-oidc
        property: client_secret
