---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base
  - google-oidc.externalsecret.yaml
  - certificate.yaml

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
    path: patches/argocd-cm.configmap.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-rbac-cm
    path: patches/argocd-rbac-cm.configmap.yaml
  - target:
      version: v1
      kind: Service
      name: argocd-server
    path: patches/argocd-server.service.yaml
  - target:
      version: v1
      kind: StatefulSet
      name: argocd-application-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 500Mi
  - target:
      version: v1
      kind: Deployment
      name: argocd-applicationset-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 50Mi
  - target:
      version: v1
      kind: Deployment
      name: argocd-notifications-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 50Mi
  - target:
      version: v1
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 25m
            memory: 100Mi
  - target:
      version: v1
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 100Mi
  - target:
      version: v1
      kind: Deployment
      name: argocd-dex-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 50Mi
  - target:
      version: v1
      kind: Deployment
      name: argocd-redis
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 50Mi
