---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-datasource
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        uid: influxdb
        url: http://influxdb2
        access: proxy
        secureJsonData:
          token: SKLoaGCGZvAilbXkFdA9w6lz5Cu2j8lK
        jsonData:
          version: Flux
          organization: home
          defaultBucket: default
          tlsSkipVerify: true