---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/name: influxdb2
spec:
  endpoints:
    - interval: 30s
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb2
