---
resources:
  requests:
    cpu: 200m
    memory: 500Mi

persistence:
  size: 1Gi

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.2.3"
    external-dns.alpha.kubernetes.io/hostname: influx.wiersma.tech.
    external-dns.alpha.kubernetes.io/ttl: 5m
  type: LoadBalancer

adminUser:
  # InfluxDB2 does not let you turn auth off. Set static passwords and tokens to use.
  organization: "home"
  user: "admin"
  password: "influx-admin"
  token: "SKLoaGCGZvAilbXkFdA9w6lz5Cu2j8lK"
